name = "worisanl-26"
main = "worker.js"
compatibility_date = "2024-09-01"

workers_dev = true

# routes အပိုင်းကို comment လုပ်ထားပါ (domain ရှိမှ ပြန်ဖွင့်ပါ)
# routes = [
#   { pattern = "cdn.mydomain.com", custom_domain = true }
# ]

[vars]
B2_REGION = "us-west-004"
B2_BUCKET_NAME = "lugyiapp"
